name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    # Setup NuGet
    - name: Setup NuGet
      uses: nuget/setup-nuget@v2

    # Restore packages for classic projects
    - name: NuGet Restore
      run: nuget restore FileUplaoder.sln

    # Setup MSBuild (from Visual Studio)
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # Build with MSBuild
    - name: Build with MSBuild
      run: msbuild FileUplaoder.sln /p:Configuration=Debug /p:Platform="Any CPU"

    # Locate vstest.console.exe
    - name: Locate vstest.console.exe
      run: Get-ChildItem "C:\Program Files\Microsoft Visual Studio\2022" -Recurse -Filter vstest.console.exe

    # Run NUnit Tests with vstest.console.exe
    - name: Run Unit Tests (classic NUnit)
      run: |
        & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" `
          "${{ github.workspace }}\**\**\bin\x64\debug\*_uTest.dll" `
          /Logger:trx `
          /ResultsDirectory:TestResults

    # Publish test results as GitHub artifact
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: TestResults
